---
- name: debian | Installing fluentd Pre-Reqs
  apt:
    name:
      - build-essential
      - ruby-dev
    state: present
  become: true

- name: debian | Adding fluentd Repo Key
  apt_key:
    url: "{{ fluentd_debian_repo_info['repo_key'] }}"
    state: present
  become: true

- name: debian | Adding fluentd Repo
  apt_repository:
    repo: "{{ fluentd_debian_repo_info['repo'] }}"
    state: present
  become: true

- name: debian | Installing fluentd Toolbelt
  apt:
    name: td-agent
    state: present
    force: true
  become: true
