---
- name: network_optimizations | optimizing network settings
  sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    state: "{{ item['state'] }}"
    sysctl_set: true
    reload: true
  become: true
  loop: "{{ fluentd_network_optimizations }}"
