---
- name: redhat | Adding FluentD Yum Repo
  yum_repository:
    name: td
    enabled: true
    description: TreasureData
    baseurl: http://packages.treasuredata.com/3/redhat/$releasever/$basearch
    gpgcheck: true
    gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing FluentD
  yum:
    name: td-agent
    state: present
  become: true
  when: ansible_distribution != "Fedora"
