---
galaxy_info:
  author: Larry Smith Jr.
  description: Installs and configures Snort IDS https://snort.org/

  license: MIT
  min_ansible_version: 1.2

  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: Ubuntu
      versions:
        - bionic
        - dingo
        - precise
        - trusty
        - vivid
        - xenial
    - name: Debian
      versions:
        - buster
        - jessie
        - wheezy
        - stretch

  galaxy_tags:
    - monitoring
    - networking
    - system

  dependencies: []
