---
- name: set_facts | Setting K8s Packages
  set_fact:
    k8s_packages:
      - kubelet={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00
      - kubernetes-cni={{ k8s_cni_version }}-00
  when: ansible_os_family == "Debian"

- name: set_facts | Setting K8s Packages
  set_fact:
    k8s_packages:
      - kubelet-{{ k8s_version }}
      - kubeadm-{{ k8s_version }}
      - kubectl-{{ k8s_version }}
      - kubernetes-cni-{{ k8s_cni_version }}
  when: ansible_os_family == "RedHat"

- name: set_facts | Setting Network CNI Facts
  set_fact:
    k8s_pod_network_config: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: k8s_pod_network_cni|lower == "weave"

- name: set_facts | Setting Network CNI Facts
  set_fact:
    k8s_pod_network_cidr: 192.168.0.0/16
    k8s_pod_network_config: https://docs.projectcalico.org/manifests/calico.yaml
  when: k8s_pod_network_cni|lower == "calico"

- name: set_facts | Setting K8s Master
  set_fact:
    k8s_master: "{{ groups[k8s_cluster_group][0] }}"
  tags:
    - k8s_cluster_nodes
    - k8s_get_dashboard
    - k8s_pods

- name: set_facts | Showing K8s Master
  debug:
    var: k8s_master

- name: set_facts | Setting K8s Advertise Address
  set_fact:
    k8s_advertise_address: "{{ hostvars[inventory_hostname]['ansible_' + k8s_advertise_address_int]['ipv4']['address'] }}"
  tags:
    - k8s_get_dashboard

- name: set_facts | Showing K8s Advertise Address
  debug:
    var: k8s_advertise_address
