---
- name: config | Configuring Kea DHCP
  template:
    src: "{{ item + '.j2' }}"
    dest: "{{ '/' + item }}"
    owner: root
    group: root
    mode: o=rw,g=r,o=r
  notify:
    - restart kea-dhcp
  become: true
  loop:
    - etc/kea/kea-dhcp-ddns.conf
    - etc/kea/kea-dhcp4.conf
