---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Hashicorp Vault
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - security
    - vault
    - hashi

dependencies: []
