---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Guacamole
  license: MIT
  role_name: guacamole
  namespace: mrlesmithjr

  min_ansible_version: "2.5"

  platforms:
    # - name: Debian
    #   versions:
    #     - buster
    #     - jessie
    #     - stretch
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - xenial

  galaxy_tags:
    - remote

dependencies: []
