---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure [Sonatype Nexus Repo OSS](https://www.sonatype.com/nexus-repository-oss)
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - system

dependencies: []
