---
- name: debian | Installing Pre-Reqs
  ansible.builtin.apt:
    name: "{{ influxdb_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding InfluxDB Repo Key
  ansible.builtin.apt_key:
    url: "{{ influxdb_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding InfluxDB Repo
  ansible.builtin.apt_repository:
    repo: "{{ influxdb_debian_repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing InfluxDB
  ansible.builtin.apt:
    name: "{{ 'influxdb=' + influxdb_version | string + '-1' }}"
    state: present
  become: true
  register: result
  until: result is successful
