---
# tasks file for ansible-influxdb
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure InfluxDB
  ansible.builtin.include_tasks: config.yml
  when: influxdb_config|bool

- name: Configure InfluxDB database(s)
  ansible.builtin.include_tasks: config_db.yml
  when: influxdb_config_databases|bool
