---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure an NGINX load balancer for HTTP/HTTPS/TCP/UDP

  license: MIT

  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
        - zesty

  galaxy_tags:
    - loadbalancing

dependencies: []
