---
# tasks file for ansible-logstash
- name: Checking To Ensure Node Meets Minimum Specs
  assert:
    that:
      - ansible_memtotal_mb > logstash_min_memory_required
    fail_msg: "{{ ansible_memtotal_mb }} < {{ logstash_min_memory_required }}"

- include_tasks: set_facts.yml

- include_tasks: debian.yml
  tags:
    - logstash
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  tags:
    - logstash
  when: ansible_os_family == "RedHat"

- include_tasks: plugins.yml
  tags:
    - logstash
    - logstash_plugins

- include_tasks: config_logstash.yml
  when: config_logstash

- include_tasks: validate_permissions.yml
  tags:
    - config_logstash
    - logstash
