---
- name: debian | Updating APT Cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: debian | Installing PHP Packages
  apt:
    name: "{{ php_debian_packages }}"
    state: present
  become: true
