---
- name: Example Playbook
  hosts: all
  vars:
    apt_mirror_populate_repos: false

  roles:
    - role: ansible-apache2
    - role: ansible-apt-mirror

- hosts: clients
  vars:
    apt_mirror_client: true
  roles:
    - role: ansible-apt-mirror
