---
# tasks file for ansible-manage-lvm
- name: Set rescan_scsi_command for old debian version
  ansible.builtin.set_fact:
    rescan_scsi_command: "/sbin/rescan-scsi-bus"
  when:
    - ansible_facts.distribution | replace(' ','') | lower == 'debian'
    - ansible_facts.distribution_release not in ('bookworm', 'sid')
    - ansible_facts.distribution_major_version is version(10, '<=')

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts.os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: centos.yml
  when: ansible_facts.os_family == "RedHat"

- name: Manage LVM
  ansible.builtin.include_tasks: manage_lvm.yml
  when:
    - lvm_groups is defined
    - manage_lvm|bool
