---
# tasks file for ansible-samba
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: samba_groups.yml
  when: samba_groups is defined

- include: samba_users.yml
  when: samba_users is defined

- include: create_shares.yml
  when: samba_shares is defined

- include: config_samba.yml

- include: create_domain.yml
  when:
    - samba_create_domain_controller|bool

- include: join_domain.yml
  when:
    - samba_create_domain_controller|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname != samba_primary_domain_controller

- include: domain_users.yml
  tags:
    - samba_domain_account_management
    - samba_domain_users
  when:
    - samba_create_domain_users is defined
    - samba_create_domain_users|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname == samba_primary_domain_controller

- include: domain_groups.yml
  tags:
    - samba_domain_account_management
    - samba_domain_groups
  when:
    - samba_create_domain_groups is defined
    - samba_create_domain_groups|bool
    - samba_domain_controllers_group is defined
    - inventory_hostname == samba_primary_domain_controller
