---
- name: samba_users | adding samba users to samba groups
  user:
    name: "{{ item[0]['name'] }}"
    groups: "{{ item[1] }}"
    append: yes
  become: true
  with_subelements:
    - "{{ samba_users }}"
    - groups

- name: samba_users | creating samba user passwords # noqa 301 306
  shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  become: true
  with_items: "{{ samba_users }}"
