---
- src: https://github.com/mrlesmithjr/ansible-aci
- src: https://github.com/mrlesmithjr/ansible-apache2
- src: https://github.com/mrlesmithjr/ansible-apf-firewall
- src: https://github.com/mrlesmithjr/ansible-apt-cacher-ng
- src: https://github.com/mrlesmithjr/ansible-apt-mirror
- src: https://github.com/mrlesmithjr/ansible-apt-sources
- src: https://github.com/mrlesmithjr/ansible-avahi
- src: https://github.com/mrlesmithjr/ansible-awx
- src: https://github.com/mrlesmithjr/ansible-awx-tower-examples
- src: https://github.com/mrlesmithjr/ansible-base
- src: https://github.com/mrlesmithjr/ansible-bashrc
- src: https://github.com/mrlesmithjr/ansible-bind
- src: https://github.com/mrlesmithjr/ansible-bird
- src: https://github.com/mrlesmithjr/ansible-bootstrap
- src: https://github.com/mrlesmithjr/ansible-bootstrap-python
- src: https://github.com/mrlesmithjr/ansible-bro-ids
- src: https://github.com/mrlesmithjr/ansible-cacti
- src: https://github.com/mrlesmithjr/ansible-cassandra
- src: https://github.com/mrlesmithjr/ansible-ceph
- src: https://github.com/mrlesmithjr/ansible-ceph-admin
- src: https://github.com/mrlesmithjr/ansible-ceph-mds
- src: https://github.com/mrlesmithjr/ansible-ceph-mon
- src: https://github.com/mrlesmithjr/ansible-ceph-osd
- src: https://github.com/mrlesmithjr/ansible-change-hostname
- src: https://github.com/mrlesmithjr/ansible-chronograf
- src: https://github.com/mrlesmithjr/ansible-chrony
- src: https://github.com/mrlesmithjr/ansible-cisco-ios-demo
- src: https://github.com/mrlesmithjr/ansible-cis-debian
- src: https://github.com/mrlesmithjr/ansible-clone-git-repos
- src: https://github.com/mrlesmithjr/ansible-cloud-init
- src: https://github.com/mrlesmithjr/ansible-cmdb
- src: https://github.com/mrlesmithjr/ansible-cobbler
- src: https://github.com/mrlesmithjr/ansible-cockpit
- src: https://github.com/mrlesmithjr/ansible-collectd
- src: https://github.com/mrlesmithjr/ansible-collection-system
- src: https://github.com/mrlesmithjr/ansible-config-interfaces
- src: https://github.com/mrlesmithjr/ansible-conntrackd
- src: https://github.com/mrlesmithjr/ansible-consul
- src: https://github.com/mrlesmithjr/ansible-consul-client
- src: https://github.com/mrlesmithjr/ansible-consul-cluster
- src: https://github.com/mrlesmithjr/ansible-control-machine
- src: https://github.com/mrlesmithjr/ansible-couchbase
- src: https://github.com/mrlesmithjr/ansible-ctdb
- src: https://github.com/mrlesmithjr/ansible-debian-autoupdates
- src: https://github.com/mrlesmithjr/ansible-digital-rebar
- src: https://github.com/mrlesmithjr/ansible-django
- src: https://github.com/mrlesmithjr/ansible-dnsmasq
- src: https://github.com/mrlesmithjr/ansible-docker
- src: https://github.com/mrlesmithjr/ansible-docker-swarm
- src: https://github.com/mrlesmithjr/ansible-domain-join
- src: https://github.com/mrlesmithjr/ansible-dovecot-ldap
- src: https://github.com/mrlesmithjr/ansible-drbd
- src: https://github.com/mrlesmithjr/ansible-dropbox-nsot
- src: https://github.com/mrlesmithjr/ansible-dumb-init
- src: https://github.com/mrlesmithjr/ansible-elasticsearch
- src: https://github.com/mrlesmithjr/ansible-elasticsearch-old
- src: https://github.com/mrlesmithjr/ansible-elk-broker
- src: https://github.com/mrlesmithjr/ansible-elk-es
- src: https://github.com/mrlesmithjr/ansible-elk-haproxy
- src: https://github.com/mrlesmithjr/ansible-elk-kibana
- src: https://github.com/mrlesmithjr/ansible-elk-pre-processor
- src: https://github.com/mrlesmithjr/ansible-elk-processor
- src: https://github.com/mrlesmithjr/ansible-elk-processors
- src: https://github.com/mrlesmithjr/ansible-elkstack
- src: https://github.com/mrlesmithjr/ansible-environments
- src: https://github.com/mrlesmithjr/ansible-es-apm-server
- src: https://github.com/mrlesmithjr/ansible-es-auditbeat
- src: https://github.com/mrlesmithjr/ansible-es-curator
- src: https://github.com/mrlesmithjr/ansible-es-filebeat
- src: https://github.com/mrlesmithjr/ansible-es-metricbeat
- src: https://github.com/mrlesmithjr/ansible-es-packetbeat
- src: https://github.com/mrlesmithjr/ansible-es-topbeat
- src: https://github.com/mrlesmithjr/ansible-etcd
- src: https://github.com/mrlesmithjr/ansible-etc-hosts
- src: https://github.com/mrlesmithjr/ansible-eve-ng
- src: https://github.com/mrlesmithjr/ansible-fail2ban
- src: https://github.com/mrlesmithjr/ansible-ferm
- src: https://github.com/mrlesmithjr/ansible-firewalld
- src: https://github.com/mrlesmithjr/ansible-fluentd
- src: https://github.com/mrlesmithjr/ansible-freenas
- src: https://github.com/mrlesmithjr/ansible-frr
- src: https://github.com/mrlesmithjr/ansible-gerrit
- src: https://github.com/mrlesmithjr/ansible-gitlab-ce
- src: https://github.com/mrlesmithjr/ansible-gitlab-runner
- src: https://github.com/mrlesmithjr/ansible-glusterfs
- src: https://github.com/mrlesmithjr/ansible-glusterfs-client
- src: https://github.com/mrlesmithjr/ansible-gocd
- src: https://github.com/mrlesmithjr/ansible-grafana
- src: https://github.com/mrlesmithjr/ansible-graphite
- src: https://github.com/mrlesmithjr/ansible-graylog
- src: https://github.com/mrlesmithjr/ansible-guacamole
- src: https://github.com/mrlesmithjr/ansible-hadoop
- src: https://github.com/mrlesmithjr/ansible-haproxy
- src: https://github.com/mrlesmithjr/ansible-hashicorp-toolbox
- src: https://github.com/mrlesmithjr/ansible-hashi-vault
- src: https://github.com/mrlesmithjr/ansible-heartbeat
- src: https://github.com/mrlesmithjr/ansible-hp-mcp
- src: https://github.com/mrlesmithjr/ansible-influxdb
- src: https://github.com/mrlesmithjr/ansible-influxdb-relay
- src: https://github.com/mrlesmithjr/ansible-inventory
- src: https://github.com/mrlesmithjr/ansible-iperf
- src: https://github.com/mrlesmithjr/ansible-iproute2
- src: https://github.com/mrlesmithjr/ansible-ipset
- src: https://github.com/mrlesmithjr/ansible-iptables
- src: https://github.com/mrlesmithjr/ansible-isc-dhcp
- src: https://github.com/mrlesmithjr/ansible-isc-dhcp-relay
- src: https://github.com/mrlesmithjr/ansible-iscsitarget
- src: https://github.com/mrlesmithjr/ansible-jekyll
- src: https://github.com/mrlesmithjr/ansible-jenkins
- src: https://github.com/mrlesmithjr/ansible-jmeter
- src: https://github.com/mrlesmithjr/ansible-juju
- src: https://github.com/mrlesmithjr/ansible-k8s
- src: https://github.com/mrlesmithjr/ansible-kafka
- src: https://github.com/mrlesmithjr/ansible-kapacitor
- src: https://github.com/mrlesmithjr/ansible-kata-containers
- src: https://github.com/mrlesmithjr/ansible-kea-dhcp
- src: https://github.com/mrlesmithjr/ansible-keepalived
- src: https://github.com/mrlesmithjr/ansible-kibana
- src: https://github.com/mrlesmithjr/ansible-knot-dns
- src: https://github.com/mrlesmithjr/ansible-kodi
- src: https://github.com/mrlesmithjr/ansible-kubernetes-ha-cluster
- src: https://github.com/mrlesmithjr/ansible-kvm
- src: https://github.com/mrlesmithjr/ansible-landscape-app
- src: https://github.com/mrlesmithjr/ansible-landscape-client
- src: https://github.com/mrlesmithjr/ansible-landscape-db
- src: https://github.com/mrlesmithjr/ansible-letsencrypt
- src: https://github.com/mrlesmithjr/ansible-lighttpd
- src: https://github.com/mrlesmithjr/ansible-linux-powercli
- src: https://github.com/mrlesmithjr/ansible-logrotate
- src: https://github.com/mrlesmithjr/ansible-logstash
- src: https://github.com/mrlesmithjr/ansible-logstash-callback
- src: https://github.com/mrlesmithjr/ansible-lsi-megaraid
- src: https://github.com/mrlesmithjr/ansible-lxd
- src: https://github.com/mrlesmithjr/ansible-maas
- src: https://github.com/mrlesmithjr/ansible-mailcatcher
- src: https://github.com/mrlesmithjr/ansible-manage-lvm
- src: https://github.com/mrlesmithjr/ansible-manage-ssh-keys
- src: https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster
- src: https://github.com/mrlesmithjr/ansible-mariadb-mysql
- src: https://github.com/mrlesmithjr/ansible-mdadm
- src: https://github.com/mrlesmithjr/ansible-memcached
- src: https://github.com/mrlesmithjr/ansible-mesosphere
- src: https://github.com/mrlesmithjr/ansible-module-chaperone
- src: https://github.com/mrlesmithjr/ansible-mongodb
- src: https://github.com/mrlesmithjr/ansible-monit
- src: https://github.com/mrlesmithjr/ansible-motd
- src: https://github.com/mrlesmithjr/ansible-m-pdns_zone
- src: https://github.com/mrlesmithjr/ansible-mssql
- src: https://github.com/mrlesmithjr/ansible-mysql
- src: https://github.com/mrlesmithjr/ansible-mysql-dynamic-inventory
- src: https://github.com/mrlesmithjr/ansible-mysql-dynamic-inventory-agent
- src: https://github.com/mrlesmithjr/ansible-nagios
- src: https://github.com/mrlesmithjr/ansible-nautobot
- src: https://github.com/mrlesmithjr/ansible-netbox
- src: https://github.com/mrlesmithjr/ansible-netdata
- src: https://github.com/mrlesmithjr/ansible-netplan
- src: https://github.com/mrlesmithjr/ansible-network-tools
- src: https://github.com/mrlesmithjr/ansible-network-tweaks
- src: https://github.com/mrlesmithjr/ansible-nexus-repo-oss
- src: https://github.com/mrlesmithjr/ansible-nfs-client
- src: https://github.com/mrlesmithjr/ansible-nfs-server
- src: https://github.com/mrlesmithjr/ansible-nginx
- src: https://github.com/mrlesmithjr/ansible-nginx-load-balancer
- src: https://github.com/mrlesmithjr/ansible-nipap
- src: https://github.com/mrlesmithjr/ansible-nodejs
- src: https://github.com/mrlesmithjr/ansible-nomad
- src: https://github.com/mrlesmithjr/ansible-ntop
- src: https://github.com/mrlesmithjr/ansible-ntp
- src: https://github.com/mrlesmithjr/ansible-observium
- src: https://github.com/mrlesmithjr/ansible-offline-yum-repo
- src: https://github.com/mrlesmithjr/ansible-opencart
- src: https://github.com/mrlesmithjr/ansible-open-iscsi
- src: https://github.com/mrlesmithjr/ansible-openjdk
- src: https://github.com/mrlesmithjr/ansible-openldap
- src: https://github.com/mrlesmithjr/ansible-opennms
- src: https://github.com/mrlesmithjr/ansible-openstack
- src: https://github.com/mrlesmithjr/ansible-openstack-base
- src: https://github.com/mrlesmithjr/ansible-openstack-block-storage-service
- src: https://github.com/mrlesmithjr/ansible-openstack-compute-service-compute
- src: https://github.com/mrlesmithjr/ansible-openstack-compute-service-controller
- src: https://github.com/mrlesmithjr/ansible-openstack-dashboard
- src: https://github.com/mrlesmithjr/ansible-openstack-identity-service
- src: https://github.com/mrlesmithjr/ansible-openstack-image-service
- src: https://github.com/mrlesmithjr/ansible-openstack-networking-service-compute
- src: https://github.com/mrlesmithjr/ansible-openstack-networking-service-controller
- src: https://github.com/mrlesmithjr/ansible-openstack-old
- src: https://github.com/mrlesmithjr/ansible-openstack-openrc
- src: https://github.com/mrlesmithjr/ansible-openvswitch
- src: https://github.com/mrlesmithjr/ansible-openvswitch-old
- src: https://github.com/mrlesmithjr/ansible-oracle-java8
- src: https://github.com/mrlesmithjr/ansible-ossec-server
- src: https://github.com/mrlesmithjr/ansible-ovirt-engine
- src: https://github.com/mrlesmithjr/ansible-owncloud
- src: https://github.com/mrlesmithjr/ansible-pacemaker
- src: https://github.com/mrlesmithjr/ansible-passenger
- src: https://github.com/mrlesmithjr/ansible-pbis-open
- src: https://github.com/mrlesmithjr/ansible-percona-xtrabackup
- src: https://github.com/mrlesmithjr/ansible-performance-tuning
- src: https://github.com/mrlesmithjr/ansible-php
- src: https://github.com/mrlesmithjr/ansible-phpipam
- src: https://github.com/mrlesmithjr/ansible-playbooks
- src: https://github.com/mrlesmithjr/ansible-plex
- src: https://github.com/mrlesmithjr/ansible-policy-based-routing
- src: https://github.com/mrlesmithjr/ansible-postfix
- src: https://github.com/mrlesmithjr/ansible-postgresql
- src: https://github.com/mrlesmithjr/ansible-powerdns
- src: https://github.com/mrlesmithjr/ansible-powerdns-authoritative
- src: https://github.com/mrlesmithjr/ansible-powerdns-dnsdist
- src: https://github.com/mrlesmithjr/ansible-powerdns-recursor
- src: https://github.com/mrlesmithjr/ansible-powershell
- src: https://github.com/mrlesmithjr/ansible-prometheus
- src: https://github.com/mrlesmithjr/ansible-prometheus-alertmanager
- src: https://github.com/mrlesmithjr/ansible-prometheus-node-exporter
- src: https://github.com/mrlesmithjr/ansible-puppet-agent
- src: https://github.com/mrlesmithjr/ansible-puppet-server
- src: https://github.com/mrlesmithjr/ansible-quagga
- src: https://github.com/mrlesmithjr/ansible-rabbitmq
- src: https://github.com/mrlesmithjr/ansible-rancid-git
- src: https://github.com/mrlesmithjr/ansible-rclone-backups
- src: https://github.com/mrlesmithjr/ansible-redis
- src: https://github.com/mrlesmithjr/ansible-rexify
- src: https://github.com/mrlesmithjr/ansible-role-chaperone
- src: https://github.com/mrlesmithjr/ansible-rpi-k8s-cluster
- src: https://github.com/mrlesmithjr/ansible-rsyslog
- src: https://github.com/mrlesmithjr/ansible-rudder
- src: https://github.com/mrlesmithjr/ansible-rundeck
- src: https://github.com/mrlesmithjr/ansible-saltstack
- src: https://github.com/mrlesmithjr/ansible-samba
- src: https://github.com/mrlesmithjr/ansible-sendmail
- src: https://github.com/mrlesmithjr/ansible-sensu
- src: https://github.com/mrlesmithjr/ansible-shorewall
- src: https://github.com/mrlesmithjr/ansible-snmpd
- src: https://github.com/mrlesmithjr/ansible-snorby
- src: https://github.com/mrlesmithjr/ansible-snort
- src: https://github.com/mrlesmithjr/ansible-spinnaker-halyard
- src: https://github.com/mrlesmithjr/ansible-squid
- src: https://github.com/mrlesmithjr/ansible-sshd
- src: https://github.com/mrlesmithjr/ansible-sssd
- src: https://github.com/mrlesmithjr/ansible-stackstorm
- src: https://github.com/mrlesmithjr/ansible-supervisor
- src: https://github.com/mrlesmithjr/ansible-suricata
- src: https://github.com/mrlesmithjr/ansible-syslog-ng
- src: https://github.com/mrlesmithjr/ansible-tcpwrappers
- src: https://github.com/mrlesmithjr/ansible-telegraf
- src: https://github.com/mrlesmithjr/ansible-tftpd-hpa
- src: https://github.com/mrlesmithjr/ansible-tftpserver
- src: https://github.com/mrlesmithjr/ansible-timezone
- src: https://github.com/mrlesmithjr/ansible-ufw
- src: https://github.com/mrlesmithjr/ansible-unbound
- src: https://github.com/mrlesmithjr/ansible-users
- src: https://github.com/mrlesmithjr/ansible-varnish
- src: https://github.com/mrlesmithjr/ansible-virtualbox
- src: https://github.com/mrlesmithjr/ansible-vmware-chaperone
- src: https://github.com/mrlesmithjr/ansible-vmware-pyvmomi
- src: https://github.com/mrlesmithjr/ansible-vsphere-management
- src: https://github.com/mrlesmithjr/ansible-windows-dns-server
- src: https://github.com/mrlesmithjr/ansible-windows-docker
- src: https://github.com/mrlesmithjr/ansible-windows-domain
- src: https://github.com/mrlesmithjr/ansible-windows-domain-controller
- src: https://github.com/mrlesmithjr/ansible-windows-iis
- src: https://github.com/mrlesmithjr/ansible-windows-powercli
- src: https://github.com/mrlesmithjr/ansible-windows-remote-desktop
- src: https://github.com/mrlesmithjr/ansible-windows-updates
- src: https://github.com/mrlesmithjr/ansible-wok
- src: https://github.com/mrlesmithjr/ansible-wordpress
- src: https://github.com/mrlesmithjr/ansible-zabbix
- src: https://github.com/mrlesmithjr/ansible-zabbix-agent
- src: https://github.com/mrlesmithjr/ansible-zabbix-old
- src: https://github.com/mrlesmithjr/ansible-zenoss
- src: https://github.com/mrlesmithjr/ansible-zfs
- src: https://github.com/mrlesmithjr/ansible-zookeeper
