---
# handlers file for ansible-haproxy
- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true
  when: not ansible_check_mode

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
  when: not ansible_check_mode
