---
- name: redhat | Installing Postfix
  yum:
    name:
      - postfix
      - mailx
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Postfix
  dnf:
    name:
      - postfix
      - mailx
    state: present
  become: true
  when: ansible_distribution == "Fedora"
