---
- name: debian | Adding deb http://deb.debian.org/debian/ sid main
  apt_repository:
    repo: deb http://deb.debian.org/debian/ sid main
    state: present
  become: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version is version('9', '!=')

- name: debian | Installing OpenJDK
  apt:
    name: openjdk-8-jre
    state: present
  become: true
  register: result
  until: result is successful
