---
- name: install | Creating Nexus User
  user:
    create_home: false
    home: /nonexistent
    name: nexus
    shell: /usr/sbin/nologin
    state: present
    system: true
  become: true

- name: install | Ensuring {{ nexus_repo_oss_install_dir }} Directory Exists
  file:
    path: "{{ nexus_repo_oss_install_dir }}"
    state: directory
  become: true

- name: install | Installing Nexus Repo OSS
  unarchive:
    creates: "{{ nexus_repo_oss_install_dir }}/nexus-{{ nexus_repo_oss_version }}/bin/nexus"
    dest: "{{ nexus_repo_oss_install_dir }}"
    group: nexus
    owner: nexus
    remote_src: true
    src: "{{ nexus_repo_oss_dl_url }}"
  become: true
  retries: 3

- name: install | Setting Permissions On Nexus Repo Dirs
  file:
    group: nexus
    owner: nexus
    path: "{{ item }}"
    recurse: true
    state: directory
  become: true
  loop:
    - "{{ nexus_repo_oss_install_dir }}/nexus-{{ nexus_repo_oss_version }}"
    - "{{ nexus_repo_oss_install_dir }}/sonatype-work"

- name: install | Configuring Nexus Repo OSS Service
  template:
    dest: /etc/systemd/system/nexus.service
    src: nexus.service.j2
  become: true
  when: ansible_service_mgr == "systemd"

- name: install | Disable Admin Wizard
  lineinfile:
    path: "{{ nexus_repo_oss_default_settings_file }}"
    line: nexus.onboarding.enabled=false
    create: true
  become: true
  notify:
    - restart nexus

- name: install | Ensuring Nexus Repo OSS Service Is Started and Enabled
  systemd:
    daemon_reload: true
    enabled: true
    name: nexus.service
    state: started
  become: true
  when: ansible_service_mgr == "systemd"

- name: install | Waiting For Nexus Repo OSS Service To Start
  wait_for:
    port: 8081

- name: install | Checking For Initial Nexus Default Admin Password
  stat:
    path: "{{ nexus_repo_oss_install_dir }}/sonatype-work/nexus{{ nexus_repo_oss_version.split('.')[0] }}/admin.password"
  register: nexus_repo_oss_default_pass_check

- name: install | Capturing Nexus Admin Password
  slurp:
    src: "{{ nexus_repo_oss_install_dir }}/sonatype-work/nexus{{ nexus_repo_oss_version.split('.')[0] }}/admin.password"
  register: _nexus_repo_oss_temp_pass
  when: nexus_repo_oss_default_pass_check.stat.exists|bool

- name: install | Setting Admin Password Fact
  set_fact:
    nexus_repo_oss_temp_pass: "{{ _nexus_repo_oss_temp_pass.content | b64decode }}"
  when: nexus_repo_oss_default_pass_check.stat.exists|bool

- name: install | Displaying Nexus Admin Password
  debug:
    msg: "Admin password: {{ nexus_repo_oss_temp_pass }}"
  when: nexus_repo_oss_default_pass_check.stat.exists|bool
