---
# tasks file for ansible-nexus-repo-oss

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'

- include_tasks: install.yml
  when: ansible_os_family != 'Windows'

- include_tasks: config.yml
