---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Prometheus Node Exporter
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - trusty
        - xenial

  galaxy_tags:
    - monitoring
dependencies: []
