---
# defaults file for ansible-awx
awx:
  # Defines the version of Ansible to install
  ansible_ver: 2.9.13

  # Container networking configuration
  # Set the awx_task and awx_web containers' search domain(s)
  container_search_domains:
    []
    # - ansible.com
    # - example.com

  # Debian pre-reqs
  debian_pre_reqs:
    - build-essential
    - git
    - libffi-dev
    - libssl-dev
    - python-dev
    - python-pip
    - python-setuptools

  # This will create or update a default admin (superuser) account in AWX, if not provided
  # then these default values are used
  default_admin_password: password
  default_admin_user: admin

  docker_compose_dir: /var/lib/awx/compose

  host_port: 80
  pg_database: awx
  # pg_hostname:            postgresql
  pg_password: awxpass
  pg_port: 5432
  pg_username: awx
  postgres_data_dir: /var/lib/awx/pgdocker

  # RedHat pre-reqs
  redhat_pre_reqs:
    - bzip2
    - gcc-c++
    - gettext
    - git
    - gmp-devel
    - libffi-devel
    - nodejs
    - npm
    - openssl-devel
    - python-crypto
    - python-devel
    - python-pip
    - python-setuptools
    - redhat-rpm-config

  repo_dir: $HOME/awx
  repo: https://github.com/ansible/awx.git

  # AWX Secret key
  # It's *very* important that this stay the same between upgrades or you will
  # lose the ability to decrypt your credentials
  secret_key: awxsecret

  task_hostname: awx

  update: true

  # Defines the version of AWX to install
  version: 14.1.0

  web_hostname: awxweb
