---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure RabbitMQ
  license: MIT
  min_ansible_version: "1.2"
  role_name: rabbitmq
  namespace: mrlesmithjr
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - clustering
    - system
dependencies: []
