---
# tasks file for ansible-snort

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_snort.yml
  when: snort_config_snort|bool

- include_tasks: config_oinkmaster.yml
  when: snort_config_oinkmaster|bool

- include_tasks: barnyard2.yml
  when: snort_barnyard2_enable|bool
