---
# tasks file for ansible-netdata

- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Netdata
  ansible.builtin.include_tasks: install.yml

- name: Configure Netdata
  ansible.builtin.include_tasks: config.yml
  when: netdata_config

- name: Update Netdata
  ansible.builtin.include_tasks: update.yml
  when: netdata_update or netdata_update_force

- name: Setup Netdata auto updates
  ansible.builtin.include_tasks: auto_updates.yml
  when: netdata_auto_updates['enabled']

- name: Uninstall Netdata
  ansible.builtin.include_tasks: uninstall.yml
  when: netdata_uninstall
  tags:
    - netdata_uninstall
