---
- name: redhat | installing apache
  dnf:
    name: httpd
    state: present
  become: true
  register: result
  until: result is successful
  when: >
        ansible_distribution == "Fedora"

- name: redhat | installing apache
  yum:
    name: httpd
    state: present
  become: true
  register: result
  until: result is successful
  when: >
        ansible_distribution != "Fedora"
