---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install various Hashicorp Utils
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - development

dependencies: []
