---
# handlers file for ansible-eve-ng
- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: true
  become: true

- name: restart ssh
  service:
    name: ssh
    state: restarted
    enabled: true
  become: true
