---
# tasks file for ansible-powerdns-authoritative
- include_tasks: pdns_accounts.yml

- include_tasks: systemd_resolved.yml
  when:
    - ansible_service_mgr == "systemd"
    - pdns_auth_systemd_resolved_disable|bool

- include_tasks: pdns_server.yml

- include_tasks: pdns_zones.yml
  when:
    - pdns_auth_create_pdns_zones is defined
    - pdns_auth_create_pdns_zones|bool

- include_tasks: pdns_records.yml
  when:
    - pdns_auth_create_records is defined
    - pdns_auth_create_records|bool
    - pdns_auth_records is defined
