---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure FluentD
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system
    - monitoring

dependencies: []
