---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure MongoDB
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial

  galaxy_tags:
    - nosql

dependencies: []
