---
galaxy_info:
  author: Larry Smith Jr.
  description: An Ansible role to install/configure InfluxDB
  role_name: influxdb
  namespace: mrlesmithjr

  license: MIT

  min_ansible_version: "2.8"
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - database

dependencies: []
