---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure KeepAliveD
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 24
        - 25
        - 26
        - 27
        - 28
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - networking

dependencies: []
