---
- name: redhat | Installing Pre-Reqs
  dnf:
    name:
      - kernel-devel
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers
      - elfutils-libelf-devel
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Adding VirtualBox GPG Key
  rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: true

- name: redhat | Installing Virtualbox
  dnf:
    name: "{{ virtualbox_dl_url + '/' + 'VirtualBox-' + virtualbox_major_ver|string + '-' + virtualbox_minor_ver|string + '_' + virtualbox_build_ver|string + '_fedora'+ansible_distribution_major_version|string+'-1.x86_64.rpm' }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Installing Virtualbox
  yum:
    name: "{{ virtualbox_dl_url + '/' + 'VirtualBox-' + virtualbox_major_ver|string + '-' + virtualbox_minor_ver|string + '_' + virtualbox_build_ver|string + '_el'+ansible_distribution_major_version|string+'-1.x86_64.rpm' }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"
