---
- name: debian | updating apt cache
  apt:
    cache_valid_time: 3600
    update_cache: true
  become: true

- name: debian | Installing Pre-Reqs
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding nodejs repo key
  apt_key:
    id: "{{ nodejs_debian_repo_info['id'] }}"
    url: "{{ nodejs_debian_repo_info['repo_key'] }}"
    state: present
  become: true

- name: debian | adding nodejs repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  with_items: "{{ nodejs_debian_repo_info['repos'] }}"

- name: debian | installing nodejs packages
  apt:
    name: "{{ nodejs_debian_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
