---
# tasks file for ansible-mdadm
#

- include_tasks: debian.yml
  when: ansible_facts.os_family == "Debian"

- include_tasks: el.yml
  when: ansible_facts.os_family == "RedHat"

- include_tasks: wipe_disks.yml
  when: >
        mdadm_force_wipe is defined and
        mdadm_force_wipe
- include_tasks: arrays.yml
