---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Ansible AWX
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - automation

dependencies: []
