---
# tasks file for ansible-haproxy
- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: OpenSUSE specific tasks
  ansible.builtin.include_tasks: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- name: Debug HAProxy SSL
  ansible.builtin.debug:
    var: haproxy_ssl

- name: Manage SSL
  ansible.builtin.include_tasks: ssl.yml
  when:
    - haproxy_ssl is defined
    - haproxy_ssl != []
    - haproxy_ssl.enabled|bool

- name: Configure HAProxy
  ansible.builtin.include_tasks: config_haproxy.yml
  when:
    - haproxy_config is defined
    - haproxy_config|bool

- name: Manage services
  ansible.builtin.include_tasks: service.yml

- name: Manage system settings
  ansible.builtin.include_tasks: sysctl.yml
