---
- name: opensuse | installing haproxy and socat
  community.general.packaging.os.zypper:
    name:
      - haproxy
      - hatop
      - socat
    state: present
  become: true
  register: result
  until: result is successful
