---
- name: redhat | installing haproxy and socat
  ansible.builtin.package:
    name:
      - haproxy
      # - hatop
      - socat
    state: present
  become: true
  register: result
  until: result is successful
