---
- name: Sysctl | Managing sysctl Settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    reload: true
  become: true
  loop: "{{ haproxy_sysctl_settings }}"
