---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure GitLab runner
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - development
dependencies: []
