---
# defaults file for ansible-es-curator
es_curator_actions:
  1:
    action:                      delete_indices
    description:                 >-
      Delete indices older than 45 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list:         True
      timeout_override:
      continue_if_exception:     False
      disable_action:            False
    filters:
      - filtertype:              pattern
        kind:                    prefix
        value:                   logstash-
        exclude:
      - filtertype:              age
        source:                  name
        direction:               older
        timestring:              '%Y.%m.%d'
        unit:                    days
        unit_count:              45
        exclude:

es_curator_config:
  client:
    hosts:
      - 127.0.0.1
    port:                        9200
    url_prefix:
    use_ssl:                     False
    certificate:
    client_cert:
    client_key:
    aws_key:
    aws_secret_key:
    aws_region:
    ssl_no_validate:             False
    http_auth:
    timeout:                     30
    master_only:                 False

  logging:
    loglevel:                    INFO
    logfile:
    logformat:                   default
    blacklist:                   ['elasticsearch', 'urllib3']

es_curator_debian_repo:          "deb [arch=amd64] https://packages.elastic.co/curator/{{ es_curator_major_version }}/debian stable main"

es_curator_elasticsearch_hosts:
  - 127.0.0.1

es_curator_repo_key:             https://packages.elastic.co/GPG-KEY-elasticsearch

es_curator_major_version:        5

es_curator_minor_version:        5.5.1
