---
- name: mysql_root_pw | setting MySQL root password
  debconf:
    name: "{{ mysql_package }}"
    question: "{{ item }}"
    value: "{{ mysql_root_password }}"
    vtype: password
  changed_when: false
  no_log: true
  become: true
  loop:
    - mysql-server/root_password
    - mysql-server/root_password_again
  when: ansible_os_family == "Debian"
