---
# Need to add EPEL Repo for python2 pip
- name: redhat | Adding EPEL Repo
  yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_python_version is version('3', '<')

- name: redhat | installing pre-reqs
  yum:
    name: "{{ mysql_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs On Fedora
  dnf:
    name: "{{ mysql_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"

- name: redhat | Installing PyMySQL
  pip:
    name: PyMySQL
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | installing mysql CentOS 6
  yum:
    name:
      - mysql-server
      - mysql
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('7', '<')

- name: redhat | Installing MySQL Fedora
  dnf:
    name:
      - mysql-server
      - mysql
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | installing mariadb mysql CentOS 7
  yum:
    name:
      - mariadb-server
      - mariadb
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('7', '>=')

- name: redhat | Ensuring mysqld Is Enabled and Starts On Boot
  service:
    name: mysqld
    state: started
    enabled: true
  become: true
  when: >
    (ansible_distribution == "CentOS" and
    ansible_distribution_version is version('7', '<')) or
    (ansible_distribution == "Fedora" and
    (ansible_distribution_version is version('24', '==') or
    ansible_distribution_version is version('25', '==')))

- name: redhat | Ensuring mariadb Service Is Enabled and Starts On Boot
  service:
    name: mariadb
    state: started
    enabled: true
  become: true
  when: >
    (ansible_distribution == "CentOS" and
    ansible_distribution_version is version('7', '>=')) or
    (ansible_distribution == "Fedora" and
    (ansible_distribution_version is version('23', '<=') or
    ansible_distribution_version is version('26', '>=')))
