---
- name: config | Listing Registered GitLab Runners
  command: gitlab-runner list
  become: true
  register: gitlab_runners
  changed_when: false

- name: config | Register GitLab Runner # noqa 102
  command: >
    gitlab-runner register --name {{ inventory_hostname }} \
    --non-interactive \
    --url {{ gitlab_runner_config['url'] }} \
    --registration-token {{ gitlab_runner_config['token'] }} \
    --executor {{ gitlab_runner_config['executor'] }} \
    --tag-list {{ gitlab_runner_tags|join(',') }}
  become: true
  when: gitlab_runners['stderr']['find']('\n{{ inventory_hostname }}') == -1
