---
# tasks file for ansible-gitlab-runner
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config.yml
  when:
    - gitlab_runner_config['configure']|bool

- include: users.yml
