---
- name: redhat | Adding Rudder Repo Key
  rpm_key:
    key: "{{ rudder_rpm_key }}"
    state: present
  become: true

- name: redhat | Adding Rudder Repo
  yum_repository:
    description: "{{ 'Rudder '+rudder_version|string }}"
    name: "{{ 'Rudder_'+rudder_version|string }}"
    baseurl: "{{ rudder_rpm_repo }}"
    gpgcheck: true
    gpgkey: "{{ rudder_rpm_key }}"
    state: present
  become: true

- name: redhat | Installing Rudder Root Server
  dnf:
    name: rudder-server-root
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"
    - inventory_hostname == rudder_root_server

- name: redhat | Installing Rudder Root Server
  yum:
    name: rudder-server-root
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - inventory_hostname == rudder_root_server

- name: redhat | Installing Rudder Agent
  dnf:
    name: rudder-agent
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"

- name: redhat | Installing Rudder Agent
  yum:
    name: rudder-agent
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
