---
# tasks file for ansible-nfs-client
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: config.yml
