---
- name: debian | Adding Microsoft Powershell Repo Key
  apt_key:
    url: "{{ linux_powercli_powershell_debian_repo_info['key'] }}"
    state: present
  become: true

- name: debian | Adding Microsoft Powershell Repo
  apt_repository:
    repo: "{{ linux_powercli_powershell_debian_repo_info['repo'] }}"
    state: present
  become: true

- name: debian | Installing Powershell
  apt:
    name: powershell
    state: present
  become: true

- name: debian | Installing Unzip
  apt:
    name: unzip
    state: present
  become: true
