---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install NodeJS
  license: MIT

  min_ansible_version: 2.5

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: Ubuntu
      versions:
        - bionic
        - dingo
        - precise
        - trusty
        - utopic
        - vivid
        - wily
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy

  galaxy_tags:
    - development

dependencies: []
