---
- name: debian | Installing Guacamole Pre-Reqs
  ansible.builtin.apt:
    name: "{{ guacamole_debian_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful
