---
# tasks file for ansible-guacamole
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Guacamole
  ansible.builtin.include_tasks: install.yml

- name: Configure Guacamole
  ansible.builtin.include_tasks: config.yml

- name: Manage Guacamole services
  ansible.builtin.include_tasks: services.yml

- name: Manage Guacamole client configurations
  ansible.builtin.include_tasks: client.yml

- name: Manage Guacamole LDAP authentication
  ansible.builtin.include_tasks: ldap.yml
  when: guacamole_ldap is defined

- name: Manage Guacamole TOTP configurations
  ansible.builtin.include_tasks: totp.yml
  when: guacamole_totp is defined
