---
- name: redhat | Enabling EPEL Repo
  ansible.builtin.yum:
    name: ["epel-release"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Enabling RPM Fusion Repos
  ansible.builtin.yum:
    name: "{{ guacamole_redhat_fusion_repos }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Guacamole Pre-Reqs
  ansible.builtin.yum:
    name: "{{ guacamole_redhat_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Guacamole Pre-Reqs
  ansible.builtin.dnf:
    name: "{{ guacamole_redhat_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"
