---
- name: interfaces | Capturing Network Interfaces
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/interface/' }}"
    user: "{{ freenas_user }}"
  register: captured_network_interfaces
  delegate_to: localhost
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Capturing VLANS
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/vlan/' }}"
    user: "{{ freenas_user }}"
  register: captured_vlan_interfaces
  delegate_to: localhost
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Capturing LAGGs
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/lagg/' }}"
    user: "{{ freenas_user }}"
  register: captured_lagg_interfaces
  delegate_to: localhost
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Setting Interfaces Config Fact
  set_fact:
    freenas_interfaces_config: "{{ lookup('template', 'interfaces_config.yaml.j2') }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Displaying Interfaces Config Fact
  debug:
    var: freenas_interfaces_config
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Creating Interfaces (Non-VLAN, Non-LAGG)
  uri:
    body: "{{ item['config'] }}"
    body_format: json
    force_basic_auth: true
    method: POST
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 201
    url: "{{ freenas_api_url + '/network/interface/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['create_interfaces'] }}"
  when: >
    item['config'] is defined and
    item['config'] != {} and
    not item['vlan_interface'] and
    not item['lagg_interface']
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Creating VLAN Interfaces
  uri:
    body: "{{ item }}"
    body_format: json
    force_basic_auth: true
    method: POST
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 201
    url: "{{ freenas_api_url + '/network/vlan/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['create_vlan_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Creating LAGG Interfaces
  uri:
    body: "{{ item }}"
    body_format: json
    force_basic_auth: true
    method: POST
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 201
    url: "{{ freenas_api_url + '/network/lagg/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['create_lagg_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network

# We need to catpure the network interfaces again after creating new interfaces
# and vlan interfaces
- name: interfaces | Capturing Network Interfaces
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/interface/' }}"
    user: "{{ freenas_user }}"
  register: captured_network_interfaces
  delegate_to: localhost
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Capturing LAGGs
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/lagg/' }}"
    user: "{{ freenas_user }}"
  register: captured_lagg_interfaces
  delegate_to: localhost
  tags:
    - freenas_interfaces
    - freenas_network

# Update config after re-capturing the network interfaces
- name: interfaces | Setting Interfaces Config Fact
  set_fact:
    freenas_interfaces_config: "{{ lookup('template', 'interfaces_config.yaml.j2') }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Updating Interfaces
  uri:
    body: "{{ item['config'] }}"
    body_format: json
    force_basic_auth: true
    method: PUT
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/interface/' + item['id']|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['update_interfaces'] }}"
  when: >
    item['config'] is defined and
    item['config'] != {}
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Updating VLAN Interfaces
  uri:
    body: "{{ item['config'] }}"
    body_format: json
    force_basic_auth: true
    method: PUT
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/network/vlan/' + item['id']|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['update_vlan_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Deleting VLAN Interfaces
  uri:
    force_basic_auth: true
    method: DELETE
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 204
    url: "{{ freenas_api_url + '/network/vlan/' + item|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['delete_vlan_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Deleting Interfaces
  uri:
    force_basic_auth: true
    method: DELETE
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 204
    url: "{{ freenas_api_url + '/network/interface/' + item|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['delete_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network

- name: interfaces | Deleting LAGG Interfaces
  uri:
    force_basic_auth: true
    method: DELETE
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 204
    url: "{{ freenas_api_url + '/network/lagg/' + item|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_interfaces_config['delete_lagg_interfaces'] }}"
  tags:
    - freenas_interfaces
    - freenas_network
