---
# tasks file for ansible-freenas
- include_tasks: system.yml
  tags:
        - freenas_system

- include_tasks: network.yml
  tags:
        - freenas_network

- include_tasks: interfaces.yml
  tags:
        - freenas_interfaces
        - freenas_network

- include_tasks: storage.yml
  tags:
        - freenas_storage

- include_tasks: groups.yml
  tags:
        - freenas_groups

- include_tasks: users.yml
  tags:
        - freenas_users

- include_tasks: services.yml
  tags:
        - freenas_services

- include_tasks: sharing.yml
  tags:
        - freenas_sharing
