---
- name: services | Capturing Services
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/services/services/' }}"
    user: "{{ freenas_user }}"
  register: freenas_services_discovered
  delegate_to: localhost
  tags:
    - freenas_services

- name: services | Displaying Discovered Services
  debug:
    var: freenas_services_discovered['json']
  tags:
    - freenas_services

- name: services | Updating Existing Services
  uri:
    body: "{{ item['config'] }}"
    body_format: json
    force_basic_auth: true
    method: PUT
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/services/services/' + item['name'] + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_services }}"
  tags:
    - freenas_services
