---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Bind DNS
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - networking

dependencies: []
