---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Logstash
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        # - 29
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - vivid
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - monitoring
    - system

dependencies: []
