---
- name: datasources | Managing Grafana Datasources
  copy:
    content: |
      apiVersion: 1
      deleteDatasources: []
      datasources:
      {{ grafana_datasources | to_nice_yaml }}
    dest: /etc/grafana/provisioning/datasources/ansible.yml
    owner: root
    group: grafana
    mode: u=rw,g=r,o=
  notify:
    - restart grafana-server
  become: true
