---
- name: debian | Updating Apt Cache
  apt:
    update_cache: true
  become: true

- name: debian | installing pre-req packages
  apt:
    name: "{{ grafana_debian_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding grafana apt key
  apt_key:
    url: "{{ grafana_gpg_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding grafana apt repo
  apt_repository:
    repo: "{{ grafana_apt_repo }}"
    state: present
  become: true

- name: debian | Installing Grafana
  apt:
    name: grafana
    state: present
  become: true
  register: result
  until: result is successful
