---
# tasks file for ansible-grafana
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config.yml
  when: grafana_config

- include_tasks: service.yml

- include_tasks: dashboards.yml
  when:
    - grafana_dashboards is defined
    - grafana_dashboards != []

- include_tasks: datasources.yml
  when:
    - grafana_datasources is defined
    - grafana_datasources != []

- include_tasks: plugins.yml
  when:
    - grafana_plugins is defined
    - grafana_plugins != []
