---
- name: Converge
  hosts: all
  vars:
    docker_set_grub_memory_limit: false
    docker_version: latest
  tasks:
    - name: Include ansible-docker
      include_role:
        name: ansible-docker
