---
# These are only required until newer version of phpIPAM in hopes of fixing php scripts
# removing all cron jobs to ensure everything is clean
- name: cron | cleaning up old cron jobs
  file:
    path: "/etc/cron.d/{{ item }}"
    state: absent
  become: true
  loop:
    - phpipam_dnsCheck
    - phpipam_fpingDiscoveryCheck
    - phpipam_resolveIP

- name: cron | adding cron job for discoveryCheck (Non-Clustered DB)
  cron:
    name: phpipam discoveryCheck
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/discoveryCheck.php"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_discoveryCheck
    state: present
  become: true
  when:
    - phpipam_define_cron_jobs|bool
    - not phpipam_db_cluster|bool

- name: cron | adding cron job for discoveryCheck (Clustered DB)
  cron:
    name: phpipam discoveryCheck
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/discoveryCheck.php"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_discoveryCheck
    state: present
  become: true
  when:
    - phpipam_define_cron_jobs|bool
    - inventory_hostname == phpipam_primary
    - phpipam_db_cluster|bool

- name: cron | adding cron job for pingCheck
  cron:
    name: phpipam pingCheck
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/pingCheck.php"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_pingCheck
    state: present
  become: true
  when: phpipam_define_cron_jobs|bool

- name: cron | adding cron job for resolveIPaddresses
  cron:
    name: phpipam resolveIPaddresses
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/resolveIPaddresses.php"
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_resolveIPaddresses
    state: present
  become: true
  when: phpipam_define_cron_jobs|bool

- name: cron | removing cron job for discoveryCheck
  cron:
    name: phpipam discoveryCheck
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/discoveryCheck.php"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_discoveryCheck
    state: absent
  become: true
  when: not phpipam_define_cron_jobs|bool

- name: cron | removing cron job for pingCheck
  cron:
    name: phpipam pingCheck
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/pingCheck.php"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_pingCheck
    state: absent
  become: true
  when: not phpipam_define_cron_jobs|bool

- name: cron | removing cron job for resolveIPaddresses
  cron:
    name: phpipam resolveIPaddresses
    job: "/usr/bin/php {{ phpipam_install_dir }}/functions/scripts/resolveIPaddresses.php"
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    user: "{{ web_owner }}"
    cron_file: phpipam_resolveIPaddresses
    state: absent
  become: true
  when: not phpipam_define_cron_jobs|bool
