---
- name: setting fact Debian apache2
  set_fact:
    web_group: www-data
    web_owner: www-data
  when: ansible_os_family == "Debian"

- name: setting fact RedHat apache
  set_fact:
    web_group: apache
    web_owner: apache
  when: ansible_os_family == "RedHat"

- name: setting PHP version (Debian)
  set_fact:
    phpenmod_command: php5enmod
    php_path: etc/php5 #no leading / for template path
    php_sqlite_package: php5-sqlite
    php_ver: 5
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '<')

- name: setting PHP version (Debian)
  set_fact:
    phpenmod_command: phpenmod
    php_path: etc/php/7.0 #no leading / for template path
    php_sqlite_package: php7.0-sqlite3
    php_ver: 7.0
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '>=')
    - ansible_distribution_version is version('10', '<')

- name: setting PHP version (Debian)
  set_fact:
    phpenmod_command: phpenmod
    php_path: etc/php/7.3 #no leading / for template path
    php_sqlite_package: php7.3-sqlite3
    php_ver: 7.3
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('10', '>=')

- name: setting PHP version (Ubuntu)
  set_fact:
    phpenmod_command: php5enmod
    php_path: etc/php5 #no leading / for template path
    php_sqlite_package: php5-sqlite
    php_ver: 5
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('14.04', '<=')

- name: setting PHP version (Ubuntu)
  set_fact:
    phpenmod_command: phpenmod
    php_path: etc/php/7.0 #no leading / for template path
    php_sqlite_package: php7.0-sqlite3
    php_ver: 7.0
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('16.04', '>=')
    - ansible_distribution_version is version('18.04', '<')

- name: setting PHP version (Ubuntu)
  set_fact:
    phpenmod_command: phpenmod
    php_path: etc/php/7.2 #no leading / for template path
    php_sqlite_package: php7.2-sqlite3
    php_ver: 7.2
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '>=')

- name: Setting Debian Packages To Install
  set_fact:
    phpipam_debian_packages:
      - fping
      - git
      - libapache2-mod-php
      - python-mysqldb
      - "php{{ php_ver }}"
      - "php{{ php_ver }}-cli"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-gmp"
      - php-pear
      - "php{{ php_ver }}-mysqlnd"
      - "php{{ php_ver }}-ldap"
      - "php{{ php_ver }}-curl"
      - "{{ php_sqlite_package }}"
      - wget
  when: ansible_os_family == "Debian"

- name: Setting RedHat Packages To Install
  set_fact:
    phpipam_redhat_packages:
      - anacron
      - fping
      - git
      - MySQL-python
      - php
      - php-cli
      - php-gmp
      - php-pear
      - php-mysqlnd
      - php-ldap
      - php-mcrypt
      - php-curl
      - wget
  when: ansible_os_family == "RedHat"
