---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure rsyslog

  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  categories:
    - monitoring
    - system

dependencies: []
