---
# defaults file for ansible-consul-client

# Define interface to bind to...(eth0|eth1|enp0s8)
consul_client_bind_interface: enp0s8

consul_client_config_dir: /etc/consul.d
consul_client_config_file: /etc/consul.conf

# https://www.consul.io/docs/agent/options.html
consul_client_configuration:
  bind_addr: "{{ hostvars[inventory_hostname]['ansible_'+consul_client_bind_interface]['ipv4']['address'] }}"
  client_addr: 127.0.0.1
  datacenter: dc1
  data_dir: /var/consul/data
  enable_syslog: true
  encrypt: qLLp1YCJzp9E/xhg11qkdQ== # Generate using 'consul keygen' - Needs to match servers
  log_level: DEBUG
  node_name: "{{ ansible_hostname }}"
  # retry_join: |
  #   {% set servers = [] %}
  #   {% for server in groups[consul_servers_group] %}
  #   {%   set _ = servers.append(hostvars[server]['ansible_'+consul_bind_interface]['ipv4']['address']) %}
  #   {% endfor %}
  #   {{ servers }}
  server: false
  ui: true

consul_client_install_dir: /usr/local/bin

# Define Consul user info to use for service
consul_client_user_info:
  user: consul
  group: consul

consul_client_version: 1.7.2

# Consul Servers info
# https://github.com/mrlesmithjr/ansible-consul

# Define Ansible group for Consul servers
consul_servers_group: consul_servers

# Define Consul bind interface for Consul servers
consul_bind_interface: enp0s8
