---
# handlers file for ansible-ntp
- name: restart ntp
  service:
    name: ntp
    state: restarted
  become: true

- name: restart ntpd
  service:
    name: ntpd
    state: restarted
  become: true
