---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure PowerDNS Authoritative
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie

  galaxy_tags:
    - networking
    - system

dependencies: []
