---
# defaults file for ansible-apt-mirror

# Defines the uri of each repository used in apt_mirror_repos
# ex.http://{{ apt_mirror_ubuntu_mirror }} will be archive.ubuntu.com/ubuntu
apt_mirror_apache_links:
  - uri: "{{ apt_mirror_ubuntu_mirror }}"
    # Defines name of symlink..ensure to change apt_mirror_client_repos to match
    distro: ubuntu

apt_mirror_apache_root_dir: /var/www/html

# Defines if running this role against a client.
apt_mirror_client: false

apt_mirror_client_repos: []
#   - "deb http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }} main restricted universe multiverse"
#   - "deb http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-backports main restricted universe multiverse"
#   - "deb http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-security main restricted universe multiverse"
#   - "deb http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-updates main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }} main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-backports main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-security main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-updates main restricted universe multiverse"
# #  - "deb http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-proposed main restricted universe multiverse"
# #  - "deb-src http://{{ apt_mirror_server }}/ubuntu {{ ansible_distribution_release|lower }}-proposed main restricted universe multiverse"

# Define directory to use as repo...default is /var/spool/apt-mirror
apt_mirror_dir: /var/spool/apt-mirror

apt_mirror_domain_name: example.org

# Defines if apt_mirror is being used...if not client will be reset...
apt_mirror_enable: false

# Defines if you would like to enable bandwidth limits Defined in apt_mirror_limit_rate
apt_mirror_enable_limit_rate: false

# Defines download rate limit in KiloBytes/thread...ex. 1Mb=125Kb..so enter 125
apt_mirror_limit_rate: 125

# Defines the number of threads
apt_mirror_nthreads: 10

# Defines if repos should be populated during install
# can set to false and allow cron job to populate.
apt_mirror_populate_repos: true

# Define list of repos to add
apt_mirror_repos: []
#   - "deb-amd64 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }} main restricted universe multiverse"
#   - "deb-amd64 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-backports main restricted universe multiverse"
#   - "deb-amd64 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-security main restricted universe multiverse"
#   - "deb-amd64 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-updates main restricted universe multiverse"
# #  - "deb-amd64 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-proposed main restricted universe multiverse"
#   - "deb-i386 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }} main restricted universe multiverse"
#   - "deb-i386 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-backports main restricted universe multiverse"
#   - "deb-i386 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-security main restricted universe multiverse"
#   - "deb-i386 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-updates main restricted universe multiverse"
# #  - "deb-i386 http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-proposed main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }} main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-backports main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-security main restricted universe multiverse"
#   - "deb-src http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-updates main restricted universe multiverse"
# #  - "deb-src http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }}-proposed main restricted universe multiverse"
#   - "deb http://{{ apt_mirror_ubuntu_mirror }} {{ ansible_distribution_release|lower }} main/debian-installer multiverse/debian-installer restricted/debian-installer universe/debian-installer"

apt_mirror_schedule: []
#   - name: apt-mirror updates
#     # Defines easy schedule....can be hourly, daily, weekly, monthly, annually,
#     # yearly or reboot..comment out if setting specific times
#     special_time: daily
# #    minute: 0
# #    hour: *
# #    day: *
# #    month: *
# #    weekday: *
#     job: /usr/bin/apt-mirror > /var/spool/apt-mirror/var/cron.log
#     cron_file: apt-mirror

# Defines if repos should be updates on a schedule...Defined in apt_mirror_schedule
apt_mirror_schedule_updates: true

# Defines server clients point to...either FQDN/hostname/IP
apt_mirror_server: "apt-mirror.{{ apt_mirror_domain_name }}"

# Define ubuntu mirror to use for ubuntu repos
apt_mirror_ubuntu_mirror: mirror.pnl.gov/ubuntu/
