---
# handlers file for ansible-postfix
- name: restart postfix
  service:
    name: postfix
    state: restarted
  become: true

- name: reload postfix
  service:
    name: postfix
    state: reloaded
  become: true
