---
galaxy_info:
  author: Larry Smith Jr.
  description: An Ansible role to install/configure Grafana

  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - buster
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
  galaxy_tags:
    - monitoring
    - system
dependencies: []
