---
- name: archlinux | Refresh Package Lists
  pacman:
    update_cache: true
  become: true

- name: archlinux | Installing Base Packages
  pacman:
    name: "{{ base_arch_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
