---
# tasks file for ansible-base
- include_tasks: set_facts.yml

- include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: debian_update_dns_nameservers.yml
  when:
    - ansible_os_family == "Debian"
    - base_update_dns_nameservers|bool

- include_tasks: debian_update_dns_search.yml
  when:
    - ansible_os_family == "Debian"
    - base_update_dns_search|bool

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
