---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure NTP
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system

dependencies: []
