---
# tasks file for ansible-consul-client

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: accounts.yml

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: services.yml
