---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Netdata
  license: MIT
  namespace: mrlesmithjr
  role_name: netdata

  min_ansible_version: "2.0"

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system
    - performance
    - monitoring

dependencies: []
