---
# defaults file for ansible-kibana

kibana:
  # Defines if Kibana should be configured
  config: false

  config_dir: /etc/kibana

  home_dir: /usr/share/kibana

  # Define Kibana Major Release
  major_version: 7.x

  # Define Kibana Minor Release
  minor_version: 7.8.0

  plugin_bin: /usr/share/kibana/kibana-plugin

  plugin_dir: /usr/share/kibana/plugins

  # Plugins do not currently work
  plugins:
    {}
    # x-pack:
    #   state: present

# https://www.elastic.co/guide/en/kibana/current/settings.html
kibana_configuration:
  elasticsearch:
    # The URLs of the Elasticsearch instances to use for all your queries.
    hosts:
      - localhost:9200

  server:
    # This setting specifies the host of the back end server. To allow remote users to connect, set the value to the
    # IP address or DNS name of the Kibana server.
    host: localhost
    # A human-readable display name that identifies this Kibana instance
    name: "{{ ansible_hostname }}"
    # Kibana is served by a back end server
    port: 5601

kibana_repo_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

kibana_repo_url: https://artifacts.elastic.co
