---
# tasks file for ansible-mysql-dynamic-inventory-agent
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: agent.yml
