---
galaxy_info:
  author: Larry Smith Jr.
  description: Installs and configures Shorewall firewall (http://shorewall.net)

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Debian
      versions:
        - buster
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - bionic
        - dingo
        - focal
        - utopic
        - vivid
        - xenial

  galaxy_tags:
    - system
    - networking
    - security
    - firewall

dependencies: []
