---
# tasks file for ansible-keepalived
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: service.yml

- include_tasks: config.yml

- include_tasks: sysctl.yml
  when: keepalived_sysctl_config|bool
