---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to configure /etc/apt/sources.list on Debian/Ubuntu systems.
  license: MIT
  min_ansible_version: "2.8"
  role_name: ansible_apt_sources
  namespace: mrlesmithjr

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system

dependencies: []
