---
# defaults file for ansible-php
php_debian_packages:
  - php
  - php-cli
  - php-cgi
  - php-curl
  - php-gd
  - php-json
  - php-ldap
  - php-mysql

php_redhat_packages:
  - php
  - php-cli
  - php-curl
  - php-devel
  - php-gd
  - php-json
  - php-ldap
  - php-mysql
