---
# tasks file for ansible-rabbitmq
- name: Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: >
        ansible_distribution == "CentOS" or
        ansible_distribution == "Red Hat Enterprise Linux" or
        ansible_distribution == "OracleLinux"

- name: Include Fedora tasks
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Manage RabbitMQ plugins
  ansible.builtin.include_tasks: rabbitmq_plugins.yml
  when: rabbitmq_plugins is defined

- name: Configure RabbitMQ
  ansible.builtin.include_tasks: config.yml
  when: rabbitmq_config_service

- name: checking to see if already clustered
  ansible.builtin.stat:
    path: /etc/rabbitmq/clustered
  become: true
  register: clustered

- name: Manage RabbitMQ clustering
  ansible.builtin.include_tasks: rabbitmq_clustering.yml
  when: >
        rabbitmq_enable_clustering and
        not clustered['stat']['exists']

- name: Manage RabbitMQ virtual hosts
  ansible.builtin.include_tasks: rabbitmq_vhosts.yml
  when: rabbitmq_extra_vhosts is defined

- name: Configure RabbitMQ
  ansible.builtin.include_tasks: rabbitmq_config.yml
  when: >
        rabbitmq_enable_clustering and
        rabbitmq_config is defined

- name: Manage RabbitMQ users
  ansible.builtin.include_tasks: rabbitmq_users.yml
  when: rabbitmq_users is defined
