---
galaxy_info:
  author: Larry Smith jr.
  description: Ansible role to install MS SQL

  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags: []

dependencies: []
