---
# We check the seal status of vault
- name: check_seal | Checking Seal Status Of HashiCorp Vault
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/seal-status' }}"
  register: _hashi_vault_sealed
