---
- name: debian | Update APT Cache
  apt:
    update_cache: true
  become: true

# We install JQ in case we want to parse any output into JSON when the
# existing output is not already in JSON
- name: debian | Installing Pre-Reqs
  apt:
    name:
      - jq
      - libcap2-bin
      - unzip
    state: present
  become: true
  register: result
  until: result is successful
