---
- include_tasks: check_seal.yml

- include_tasks: unseal.yml
  when: _hashi_vault_sealed.json.sealed|bool

# The default status codes are:
# 200 if initialized, unsealed, and active
# 429 if unsealed and standby
# 501 if not initialized
# 503 if sealed
- name: health | Checking HashiCorp Vault Health
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/health' }}"
    status_code: 200,429,501,503
  register: _hashi_vault_sever_health

- include_tasks: check_seal.yml

- include_tasks: seal.yml
  when: not _hashi_vault_sealed.json.sealed|bool

- name: health | Showing HashiCorp Vault Health
  debug:
    var: _hashi_vault_sever_health.json
