---
- include_tasks: check_seal.yml

- include_tasks: unseal.yml
  when: _hashi_vault_sealed.json.sealed|bool

- name: leader | Checking HashiCorp Vault Leader
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/leader' }}"
  register: _hashi_vault_sever_leader

- include_tasks: check_seal.yml

- include_tasks: seal.yml
  when: not _hashi_vault_sealed.json.sealed|bool

- name: leader | Showing HashiCorp Vault Leader
  debug:
    var: _hashi_vault_sever_leader.json
