---
# tasks file for ansible-hashi-vault

- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: account.yml

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: service.yml

- include_tasks: init.yml

- include_tasks: key_status.yml
  when: hashi_vault_show_key_status|bool

- include_tasks: secrets.yml
  when: hashi_vault_manage_secrets|bool

- include_tasks: health.yml
  when: hashi_vault_show_health_status|bool

- include_tasks: leader.yml
  when: hashi_vault_show_leader|bool

- include_tasks: mounts.yml
  when: hashi_vault_show_mounts|bool

- include_tasks: policies.yml
  when: hashi_vault_show_policies|bool

- name: Flush Handlers
  meta: flush_handlers

- include_tasks: check_seal.yml
  when:
    - hashi_vault_remain_unsealed|bool

- include_tasks: unseal.yml
  when:
    - hashi_vault_remain_unsealed|bool
