---
- include_tasks: check_seal.yml

- include_tasks: unseal.yml

- name: policies | Capturing List Of Configured HashiCorp Vault Policies
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/policy' }}"
    headers:
      X-Vault-Token: "{{ _hashi_vault_unseal_keys.root_token }}"
    return_content: true
  no_log: true
  register: _hashi_vault_sever_policies_list
  when: inventory_hostname == hashi_vault_master

- name: Policies | Setting Facts For Policy Lists
  set_fact:
    _hashi_vault_policy_list: "{{ _hashi_vault_sever_policies_list.content|from_json }}"
  when: inventory_hostname == hashi_vault_master

- name: policies | Reading Rules For HashiCorp Vault Policies
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/policy/'+item }}"
    headers:
      X-Vault-Token: "{{ _hashi_vault_unseal_keys.root_token }}"
    return_content: true
  no_log: true
  register: _hashi_vault_sever_policies_read
  loop: "{{ _hashi_vault_policy_list['keys'] }}"
  when: inventory_hostname == hashi_vault_master

- include_tasks: check_seal.yml

- include_tasks: seal.yml

- name: policies | Showing List Of HashiCorp Vault Policies
  debug:
    var: _hashi_vault_policy_list['keys']
  when: inventory_hostname == hashi_vault_master
