---
- name: redhat | Enabling EPEL-Release
  yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  package:
    name:
      - jq
      - unzip
    state: present
  become: true
  register: result
  until: result is successful
