---
- include_tasks: unseal_keys.yml

# We seal vault to ensure that it is sealed
- name: seal | Sealing HashiCorp Vault
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/seal' }}"
    headers:
      X-Vault-Token: "{{ _hashi_vault_unseal_keys.root_token }}"
    method: PUT
    status_code: 204
  register: _hashi_vault_sealed
  no_log: true
  when:
    - inventory_hostname == hashi_vault_master
    - not _hashi_vault_sealed.json.sealed|bool
