---
- include_tasks: check_seal.yml

- include_tasks: unseal.yml
  when: _hashi_vault_sealed.json.sealed

- include_tasks: check_seal.yml

- include_tasks: seal.yml
  when: not _hashi_vault_sealed.json.sealed
