---
# Non TLS
- name: set_facts | Setting Facts
  set_fact:
    hashi_vault_server_url: "{{ 'http://'+hashi_vault_configuration.listener.0.tcp.address }}"
  when: hashi_vault_configuration.listener.0.tcp.tls_disable|bool

# TLS
- name: set_facts | Setting Facts
  set_fact:
    hashi_vault_server_url: "{{ 'https://'+hashi_vault_configuration.listener.0.tcp.address }}"
  when: not hashi_vault_configuration.listener.0.tcp.tls_disable|bool
