---
- include_tasks: unseal_keys.yml

# We unseal vault in order to read secrets
# We must iterate through all keys in order to reach the hashi_vault_secret_threshold
- name: unseal | Unsealing HashiCorp Vault
  uri:
    url: "{{ hashi_vault_server_url+'/v1/sys/unseal' }}"
    body:
      key: "{{ item }}"
    body_format: json
    method: PUT
  register: _hashi_vault_unsealed
  no_log: true
  loop: "{{ _hashi_vault_unseal_keys['keys'] }}"
  when:
    - _hashi_vault_sealed.json.sealed|bool
